services:
  - type: web
    name: gruvi
    env: ruby
    buildCommand: bundle install && bundle exec rake db:migrate && bundle exec rake assets:precompile && bundle exec rake assets:clean
    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: gruvi-db
          property: connectionString

databases:
  - name: gruvi-db
    databaseName: gruvi_production
    plan: starter
