services:
  - type: web
    name: gruvi
    env: ruby
    buildCommand: bundle install && bundle exec rake assets:precompile && bundle exec rake assets:clean
    startCommand: bundle exec rake db:migrate && bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: TMDB_API_KEY
        sync: false
    disk:
      name: gruvi-storage
      mountPath: /opt/render/project/src/storage
      sizeGB: 1

databases:
  - name: gruvi-db
    databaseName: gruvi_production
    plan: starter
